/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-iNETS_BeamManager
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_INETS_BEAMMANAGER_API_H
#define INCLUDED_INETS_BEAMMANAGER_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_iNETS_BeamManager_EXPORTS
#define INETS_BEAMMANAGER_API __GR_ATTR_EXPORT
#else
#define INETS_BEAMMANAGER_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_INETS_BEAMMANAGER_API_H */
