find_package(PkgConfig)

PKG_CHECK_MODULES(PC_GR_INETS_PACKETIZEDLINK gnuradio-iNETS_PacketizedLink)

FIND_PATH(
    GR_INETS_PACKETIZEDLINK_INCLUDE_DIRS
    NAMES gnuradio/iNETS_PacketizedLink/api.h
    HINTS $ENV{INETS_PACKETIZEDLINK_DIR}/include
        ${PC_INETS_PACKETIZEDLINK_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    GR_INETS_PACKETIZEDLINK_LIBRARIES
    NAMES gnuradio-iNETS_PacketizedLink
    HINTS $ENV{INETS_PACKETIZEDLINK_DIR}/lib
        ${PC_INETS_PACKETIZEDLINK_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
          )

include("${CMAKE_CURRENT_LIST_DIR}/gnuradio-iNETS_PacketizedLinkTarget.cmake")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GR_INETS_PACKETIZEDLINK DEFAULT_MSG GR_INETS_PACKETIZEDLINK_LIBRARIES GR_INETS_PACKETIZEDLINK_INCLUDE_DIRS)
MARK_AS_ADVANCED(GR_INETS_PACKETIZEDLINK_LIBRARIES GR_INETS_PACKETIZEDLINK_INCLUDE_DIRS)
