#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2019 iNETS, RWTH Aachen University.
# Author: Florian Wischeler
# Modified by Berk Acikgoez, 2024.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

import cruijff
import time

# verify the desired values
trx_frequency = 27.45e9
initial_TX_BF_RF_gain = 0x44
initial_TX_BB_gain = 0x1
initial_TX_BB_IQ_gain = 0xFF

unit_name = "SNSP210073" # change this for different modules

evkplatform_type = "MB1"
custom_beambook_suffix = ""

do_lo_leakage_cal = False
ref_freq = 122.88e6
ref_is_diff = True
rfm_type = "BFM02003"

trx_cruijff = cruijff.Cruijff(unit_name = unit_name, evkplatform_type = evkplatform_type, ref_cfg = {'freq': ref_freq, 'is_diff': ref_is_diff}, rfm_type = rfm_type)

trx_accessible = trx_cruijff is not None and hasattr(trx_cruijff, 'chip_present_status')

if hasattr(trx_cruijff, 'regs') and trx_accessible:
    print('[EVK02001 Init TX]: Starting initialization now!!!')
   
    trx_cruijff.reset()
   
    if do_lo_leakage_cal:
        trx_cruijff.run_tx_lo_leakage_cal(custom_beambook_suffix = custom_beambook_suffix)
    
    trx_cruijff.runTx(trx_frequency)
    trx_cruijff.regs.wrrd('trx_tx_on', 0x1fffff) # activate all RF paths
    print('Current state: ', trx_cruijff.state())
    
    trx_cruijff.tx.bf.awv.bbp.set_selected_beambook(0)
    print("Current TX beambook = " + str(trx_cruijff.tx.bf.awv.bbp.get_selected_beambook()))

    trx_cruijff.regs.wr('tx_bfrf_gain', initial_TX_BF_RF_gain)
    trx_cruijff.regs.wr('tx_bb_gain', initial_TX_BB_gain)
    trx_cruijff.regs.wr('tx_bb_iq_gain', initial_TX_BB_IQ_gain)
    print("[EVK02001 Init TX]: TX default gains set")
    
    print('AGC control:', trx_cruijff.regs.rd('agc_int_en_ctrl'))
    print('[EVK02001 Init TX]: Initialization of antenna array evaluation kit completed.')
    
    print("[EVK02001 Init TX]: You can now connect the SPI connector and use direct SPI control. The following SPI read error is generated by the USB FTDI chip which not cannot communicate over SPI anymore. This is intended.")
    print("[EVK02001 Init TX]: After switching up the (four upper-most) SW3 inputs, press Ctrl+C to continue.")
    
    trx_cruijff.evkplatform.drv.spioff()
    
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print("\n[EVK02001 Init TX]: SPI set, terminating...")
        exit()
else:
    print("[EVK02001 Init TX]: Antenna array initialisation failed!")
