/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(baseband_derotation.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(41a0d7ad3c436106781a7870805626ba)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/iNETS_PacketizedLink/baseband_derotation.h>
// pydoc.h is automatically generated in the build directory
#include <baseband_derotation_pydoc.h>

void bind_baseband_derotation(py::module& m)
{

    using baseband_derotation    = ::gr::iNETS_PacketizedLink::baseband_derotation;


    py::class_<baseband_derotation, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<baseband_derotation>>(m, "baseband_derotation", D(baseband_derotation))

        .def(py::init(&baseband_derotation::make),
           py::arg("mu"),
           py::arg("constellation"),
           D(baseband_derotation,make)
        )
        



        ;




}








