/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(baseband_derotation_tagged_stream.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a06da16a00b90d83ae365985dfa98dcc)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/iNETS_PacketizedLink/baseband_derotation_tagged_stream.h>
// pydoc.h is automatically generated in the build directory
#include <baseband_derotation_tagged_stream_pydoc.h>

void bind_baseband_derotation_tagged_stream(py::module& m)
{

    using baseband_derotation_tagged_stream    = ::gr::iNETS_PacketizedLink::baseband_derotation_tagged_stream;


    py::class_<baseband_derotation_tagged_stream, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<baseband_derotation_tagged_stream>>(m, "baseband_derotation_tagged_stream", D(baseband_derotation_tagged_stream))

        .def(py::init(&baseband_derotation_tagged_stream::make),
           py::arg("mu"),
           D(baseband_derotation_tagged_stream,make)
        )
        



        ;




}








