/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(constellation_decoder_tagged_stream.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(585f53ae7db98f3388d8bed9992ec2ae)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/iNETS_PacketizedLink/constellation_decoder_tagged_stream.h>
// pydoc.h is automatically generated in the build directory
#include <constellation_decoder_tagged_stream_pydoc.h>

void bind_constellation_decoder_tagged_stream(py::module& m)
{

    using constellation_decoder_tagged_stream    = ::gr::iNETS_PacketizedLink::constellation_decoder_tagged_stream;


    py::class_<constellation_decoder_tagged_stream, gr::block, gr::basic_block,
        std::shared_ptr<constellation_decoder_tagged_stream>>(m, "constellation_decoder_tagged_stream", D(constellation_decoder_tagged_stream))

        .def(py::init(&constellation_decoder_tagged_stream::make),
           py::arg("mcs_tag_name"),
           D(constellation_decoder_tagged_stream,make)
        )
        



        ;




}








