/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(estimate_dBm_ff.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(fd83f9decd5ddfe38348e4fa5d9397ee)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/iNETS_PacketizedLink/estimate_dBm_ff.h>
// pydoc.h is automatically generated in the build directory
#include <estimate_dBm_ff_pydoc.h>

void bind_estimate_dBm_ff(py::module& m)
{

    using estimate_dBm_ff    = ::gr::iNETS_PacketizedLink::estimate_dBm_ff;


    py::class_<estimate_dBm_ff, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<estimate_dBm_ff>>(m, "estimate_dBm_ff", D(estimate_dBm_ff))

        .def(py::init(&estimate_dBm_ff::make),
           py::arg("alpha"),
           py::arg("sps"),
           py::arg("N"),
           D(estimate_dBm_ff,make)
        )
        



        ;




}








