/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(multiply_length_tag_tagged_stream.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7e98765649a3293e43f6568ea1655865)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/iNETS_PacketizedLink/multiply_length_tag_tagged_stream.h>
// pydoc.h is automatically generated in the build directory
#include <multiply_length_tag_tagged_stream_pydoc.h>

void bind_multiply_length_tag_tagged_stream(py::module& m)
{

    using multiply_length_tag_tagged_stream    = ::gr::iNETS_PacketizedLink::multiply_length_tag_tagged_stream;


    py::class_<multiply_length_tag_tagged_stream, gr::block, gr::basic_block,
        std::shared_ptr<multiply_length_tag_tagged_stream>>(m, "multiply_length_tag_tagged_stream", D(multiply_length_tag_tagged_stream))

        .def(py::init(&multiply_length_tag_tagged_stream::make),
           py::arg("lengthtagname"),
           py::arg("mcstagname"),
           D(multiply_length_tag_tagged_stream,make)
        )
        



        ;




}








