/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(phy_header_payload_demux.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(bf5003cb132d8351feb740a71dab01bf)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/iNETS_PacketizedLink/phy_header_payload_demux.h>
// pydoc.h is automatically generated in the build directory
#include <phy_header_payload_demux_pydoc.h>

void bind_phy_header_payload_demux(py::module& m)
{

    using phy_header_payload_demux    = ::gr::iNETS_PacketizedLink::phy_header_payload_demux;


    py::class_<phy_header_payload_demux, gr::block, gr::basic_block,
        std::shared_ptr<phy_header_payload_demux>>(m, "phy_header_payload_demux", D(phy_header_payload_demux))

        .def(py::init(&phy_header_payload_demux::make),
           py::arg("header_len"),
           py::arg("symbols_per_header_byte"),
           py::arg("guard_interval"),
           py::arg("length_tag_key"),
           py::arg("mcs_tag_key"),
           py::arg("trigger_tag_key"),
           py::arg("output_symbols"),
           py::arg("itemsize"),
           py::arg("timing_tag_key"),
           py::arg("samp_rate"),
           py::arg("special_tags"),
           py::arg("header_padding"),
           D(phy_header_payload_demux,make)
        )
        



        ;




}








