/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(repack_bits_tagged_stream.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3e9b9045ad551e694499f9f6e263c997)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/iNETS_PacketizedLink/repack_bits_tagged_stream.h>
// pydoc.h is automatically generated in the build directory
#include <repack_bits_tagged_stream_pydoc.h>

void bind_repack_bits_tagged_stream(py::module& m)
{

    using repack_bits_tagged_stream    = ::gr::iNETS_PacketizedLink::repack_bits_tagged_stream;


    py::class_<repack_bits_tagged_stream, gr::tagged_stream_block, gr::block, gr::basic_block,
        std::shared_ptr<repack_bits_tagged_stream>>(m, "repack_bits_tagged_stream", D(repack_bits_tagged_stream))

        .def(py::init(&repack_bits_tagged_stream::make),
           py::arg("mode"),
           py::arg("len_tag_key") = "paket_len",
           py::arg("mcs_tag_key") = "mcs",
           py::arg("align_output") = false,
           py::arg("endianness") = ::gr::endianness_t::GR_LSB_FIRST,
           D(repack_bits_tagged_stream,make)
        )
        



        ;




}








