find_package(PkgConfig)

PKG_CHECK_MODULES(PC_GR_INETS_SIVERSCONTROL gnuradio-iNETS_SIVERSControl)

FIND_PATH(
    GR_INETS_SIVERSCONTROL_INCLUDE_DIRS
    NAMES gnuradio/iNETS_SIVERSControl/api.h
    HINTS $ENV{INETS_SIVERSCONTROL_DIR}/include
        ${PC_INETS_SIVERSCONTROL_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    GR_INETS_SIVERSCONTROL_LIBRARIES
    NAMES gnuradio-iNETS_SIVERSControl
    HINTS $ENV{INETS_SIVERSCONTROL_DIR}/lib
        ${PC_INETS_SIVERSCONTROL_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
          )

include("${CMAKE_CURRENT_LIST_DIR}/gnuradio-iNETS_SIVERSControlTarget.cmake")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GR_INETS_SIVERSCONTROL DEFAULT_MSG GR_INETS_SIVERSCONTROL_LIBRARIES GR_INETS_SIVERSCONTROL_INCLUDE_DIRS)
MARK_AS_ADVANCED(GR_INETS_SIVERSCONTROL_LIBRARIES GR_INETS_SIVERSCONTROL_INCLUDE_DIRS)
